HEADERS = isNumber.c
CC = gcc
CFLAGS = -Wall -std=gnu11 -ggdb

swap: swap.c
	$(CC) $(CFLAGS) -o swap swap.c

point: point.c
	$(CC) $(CFLAGS) -o point point.c

geo: geo.c
	$(CC) $(CFLAGS) -o geo geo.c

clean:
	-rm -f *.o
